---
- name: Update Apt Caches
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install Requried Software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - mysql-server
    - php5-mysql
    - php5
    - libapache-mod-php5
    - php5-mcrypt
    - python-mysqldb
